import os
import re
import psycopg2
from psycopg2.extras import RealDictCursor
from backend.core.config import MP_READINESS_DATA_PATH, DB_URL

class IntegrityError(Exception):
    pass

class PgCursorWrapper:
    def __init__(self, cursor):
        self._cursor = cursor

    def _convert_sql(self, sql):
        # Prevent parameter format issues, convert SQLite ? to Postgres %s
        parts = re.split(r"('[^']*')", sql)
        for i in range(0, len(parts), 2):
            parts[i] = parts[i].replace('?', '%s')
        return ''.join(parts)

    def execute(self, sql, params=None):
        try:
            self._cursor.execute(self._convert_sql(sql), params)
            return self
        except psycopg2.IntegrityError as e:
            raise IntegrityError(str(e))

    def executemany(self, sql, params_seq):
        try:
            self._cursor.executemany(self._convert_sql(sql), params_seq)
            return self
        except psycopg2.IntegrityError as e:
            raise IntegrityError(str(e))

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchmany(self, size):
        return self._cursor.fetchmany(size)

    @property
    def lastrowid(self):
        # Assuming the last inserted row is generated by a sequence, LASTVAL() works per session.
        self._cursor.execute("SELECT LASTVAL()")
        res = self._cursor.fetchone()
        return res['lastval'] if res else None


class PgConnectionWrapper:
    def __init__(self, conn):
        self._conn = conn

    def cursor(self):
        return PgCursorWrapper(self._conn.cursor(cursor_factory=RealDictCursor))

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def get_db():
    conn = psycopg2.connect(DB_URL)
    return PgConnectionWrapper(conn)

def sanitize_folder_name(name: str) -> str:
    if not name: return "Unknown"
    sanitized = re.sub(r'[\\\\/*?:"<>|]', "_", str(name)).strip()
    return sanitized if sanitized else "Unknown"

def get_version_dir_from_checklist(model_checklist_id: int, version_no: str) -> str:
    conn = get_db()
    cursor = conn.cursor()
    
    cursor.execute("SELECT model_id, team, level_1, level_2 FROM model_checklist WHERE id = ?", (model_checklist_id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        return ""
    model_id, team, level_1, level_2 = row['model_id'], row['team'], row['level_1'], row['level_2']
    
    cursor.execute("SELECT name FROM models WHERE id = ?", (model_id,))
    model_row = cursor.fetchone()
    conn.close()
    if not model_row:
        return ""
    model_name = model_row['name']
    
    s_model = sanitize_folder_name(model_name)
    s_team = sanitize_folder_name(team)
    s_l1 = sanitize_folder_name(level_1)
    s_l2 = sanitize_folder_name(level_2)
    return os.path.join(MP_READINESS_DATA_PATH, s_model, s_team, s_l1, s_l2, version_no).replace("\\", "/")

def get_version_dir(version_id: int) -> str:
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("SELECT model_checklist_id, version_no FROM document_versions WHERE id = ?", (version_id,))
    row = cursor.fetchone()
    conn.close()
    if not row:
        return ""
    return get_version_dir_from_checklist(row['model_checklist_id'], row['version_no'])

def check_pessimistic_config_lock(cursor, user):
    import time
    cursor.execute("SELECT config_updated_at, last_updated_by FROM app_config WHERE id = 1")
    row = cursor.fetchone()
    locked_at = row['config_updated_at'] if row and row['config_updated_at'] else 0
    locked_by = row['last_updated_by'] if row and row['last_updated_by'] else ""
    
    if locked_by and locked_by != user['fullname'] and int(time.time()) - locked_at < 600:
        return f"{locked_by} đang chỉnh sửa model config. Bạn không thể thao tác vào lúc này."
    if locked_by == user['fullname'] and int(time.time()) - locked_at >= 600:
        return "Khóa đã hết hạn, vui lòng tải lại trang."
    return None

def check_pessimistic_admin_lock(cursor, user):
    import time
    cursor.execute("SELECT config_updated_at, last_updated_by FROM app_config WHERE id = 2")
    row = cursor.fetchone()
    locked_at = row['config_updated_at'] if row and row['config_updated_at'] else 0
    locked_by = row['last_updated_by'] if row and row['last_updated_by'] else ""
    
    if locked_by and locked_by != user['fullname'] and int(time.time()) - locked_at < 600:
        return f"{locked_by} đang chỉnh sửa Admin Management. Bạn không thể thao tác vào lúc này."
    if locked_by == user['fullname'] and int(time.time()) - locked_at >= 600:
        return "Khóa đã hết hạn, vui lòng tải lại trang."
    return None

def check_pessimistic_lock(cursor, checklist_id, user):
    cursor.execute("SELECT locked_by, locked_at FROM model_checklist WHERE id = ?", (checklist_id,))
    lock_row = cursor.fetchone()
    if lock_row:
        import time
        locked_by, locked_at = lock_row['locked_by'], lock_row['locked_at']
        username = user['fullname'] + ' (' + user['username'] + ')'
        if locked_by and locked_by != username:
            if locked_at and locked_at.isdigit() and int(time.time()) - int(locked_at) < 1800:
                return f"{locked_by} đang chỉnh sửa, bạn không thể thao tác vào lúc này."
    return None

def get_model_statuses(cursor):
    cursor.execute("""
        SELECT mc.model_id, 
               COUNT(mc.id) as total_items, 
               SUM(CASE WHEN (
                   SELECT dv.status 
                   FROM document_versions dv 
                   WHERE dv.model_checklist_id = mc.id 
                   ORDER BY dv.id DESC LIMIT 1
               ) = 'Approved' THEN 1 ELSE 0 END) as approved_items
        FROM model_checklist mc
        GROUP BY mc.model_id
    """)
    stats = {}
    for r in cursor.fetchall():
        total = r['total_items']
        approved = r['approved_items'] or 0
        pct = f"{(approved / total * 100):.1f}%" if total > 0 else "0.0%"
        stats[r['model_id']] = pct
    return stats
